<a href="https://colab.research.google.com/github/alurusaivahini-dotcom/trail/blob/main/customer_order.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
df=pd.read_csv("/content/orders.csv")
df.head()

,order_id,customer_name,product,quantity,unit_price,order_date,status
0,1001,Alice Johnson,Laptop,1.0,85000.0,2024-01-15,delivered
1,1002,Bob Smith,Mouse,3.0,499.0,2024-01-16,pending
2,1003,Carol White,Monitor,2.0,15000.0,NaN,delivered
3,1004,Dave Brown,Keyboard,NaN,1200.0,2024-01-18,cancelled
4,1005,Eva Green,Laptop,1.0,85000.0,2024-01-19,delivered

In [13]:
df.tail()

,order_id,customer_name,product,quantity,unit_price,order_date,status
15,1016,Paul Harris,Mouse,6.0,499.0,2024-01-30,pending
16,1017,Quinn Martin,Monitor,NaN,14500.0,2024-01-31,delivered
17,1018,Rachel King,Laptop,1.0,85000.0,NaN,delivered
18,1019,Sam Wright,Keyboard,3.0,1200.0,2024-02-01,cancelled
19,1020,Tina Baker,USB Hub,2.0,799.0,2024-02-02,pending

In [15]:
df.shape

(20, 7)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       20 non-null     int64
 1   customer_name  20 non-null     object
 2   product        20 non-null     object
 3   quantity       16 non-null     float64
 4   unit_price     20 non-null     float64
 5   order_date     16 non-null     object
 6   status         20 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 1.2+ KB

In [21]:
df.describe()

         order_id   quantity    unit_price
count    20.00000  16.000000     20.000000
mean   1010.50000   2.437500  20224.600000
std       5.91608   1.504161  33573.389607
min    1001.00000   1.000000    499.000000
25%    1005.75000   1.000000    799.000000
50%    1010.50000   2.000000   2500.000000
75%    1015.25000   3.000000  14625.000000
max    1020.00000   6.000000  85000.000000